---

- name: deploy binary
  copy: src="{{ resources_dir }}/bin/tikv-server" dest="{{ item[deploy_dir] | defalut(deploy_dir) }}/bin/" mode=0755 backup=yes
  register: tikv_binary
  with_items: "{{ instances[inventory_hostname] }}"

- name: backup bianry file
  command: mv "{{ tikv_binary.backup_file }}" "{{ backup_dir }}"
  when: tikv_binary.changed and tikv_binary.backup_file is defined

- name: create run script
  template:
    src: "run_{{ role_name }}_binary.sh.j2"
    dest: "{{ item[deploy_dir] | defalut(deploy_dir) }}/scripts/run_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items: "{{ instances[inventory_hostname] }}"
  vars:
    role_status_dir: status/{{ role_name }}
    deploy_dir: "{{ item[deploy_dir] | defalut(deploy_dir) }}"
    tikv_port: "{{ item[tikv_port] | defalut(tikv_port) }}"
  register: tikv_script

- name: backup script file
  command: mv "{{ tikv_script.backup_file }}" "{{ backup_dir }}"
  when: tikv_script.changed and tikv_script.backup_file is defined

- include_tasks: "{{ process_supervision }}_deployment.yml"
